name: Deploy to ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO }} .
          docker tag ${{ secrets.ECR_REPO }} ${{ secrets.ECR_URL }}:latest
          docker push ${{ secrets.ECR_URL }}:latest

      - name: Deploy using Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="subnet_id=${{ secrets.SUBNET_ID }}" \
            -var="sg_id=${{ secrets.SG_ID }}"
